/*
 * Problem: Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 *
 * Answer: 4613732 
 */

#include <stdio.h>
#define MAX 4000000

int main()
{
    int sum = 2;
    int i = 0;
    int two_before = 1;
    int one_before = 2;
    int this_one = 0;
    while (this_one < MAX)
    {
        this_one = two_before + one_before;
        if (this_one % 2 == 0)
            sum += this_one;
        two_before = one_before;
        one_before = this_one;
    }
    printf("%d\n", sum);
}
